version: '3.8'

services:
  # NestJS API Docker instance - Uncomment to run container with API instance 
  # app:
  #   build:
  #     context: ../
  #     dockerfile: ./Dockerfile
  #   container_name: nestjs-api
  #   restart: unless-stopped
  #   environment:
  #     - MONGO_DB_URL=mongodb://root:example@mongodb:27017/example?authSource=admin
  #     - JWT_SECRET=MY_SECRET_EXAMPLE
  #     - AWS_ACCESS_KEY=minioadmin
  #     - AWS_SECRET_KEY=minioadmin
  #     - AWS_ENDPOINT=http://minio:9000
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb

  minio:
    image: minio/minio
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=minioadmin"
      - "MINIO_SECRET_KEY=minioadmin"
    ports:
      - "9000:9000"
      - "9001:9001"
    command:  minio server --console-address ":9001" /data
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb